### ISSUE TITLE
mxchip_az3166 upgrading mxchip sdk

### ISSUE THREAD

**Issue by jbrumwell** [platformio/platform-ststm32#157]
Hi,

New to platformio and arduino, came across an issue;

```
framework-arduinostm32mxchip/libraries/AudioV2/src/AudioClassV2.h:8:22: fatal error: NAU88C10.h: No such file or directory
```
Which seems to have been fixed in their `1.3.3` release here https://github.com/Microsoft/devkit-sdk/issues/758

Is there a way for me to update the sdk in platformio to their latest release `1.5.1`?

platform.ini

```
[env:mxchip_az3166]
platform = ststm32
board = mxchip_az3166
framework = arduino
```

**Comment by fmuntean** [comment]
I see nobody seems to pay attention to this and not sure who is the owner of this board inside the Platform IO.
However now the platform IO version is very old the board is using a much newer SDK v1.6.2
Can somebody update to the latest SDK please?
Otherwise will have to move the project out of PlatformIO in order to use this board.
