### ISSUE TITLE
Why do bluepill_f103c8 and genericSTM32F103C8 have different cores and frameworks?

### ISSUE THREAD

**Issue by greygraphics** [platformio/platform-ststm32#250]
Should the generic version not support the same frameworks as the bluepill, at least CMSIS, as they are the same processor.

**Comment by valeros** [comment]
Thanks! I added CMSIS framework to all generic boards, just install the development version of the platform and you should be able to compile the basic example. As for the Arduino core, there are two separate implementations of Arduino frameworks for STM microcontrollers - maple core and official one. We use the official implementation as the default core, but since the generic boards were taken from the maple implementation, their default core is maple.
