### ISSUE TITLE
Pio always builds everything

### ISSUE THREAD

**Issue by fazerlicourice7** [platformio/platform-ststm32#532]
- [X ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Mac OS Big Sur 11.2.3

**PlatformIO Version** (`platformio --version`): 5.1.1

### Description of problem

According to this [post](https://community.platformio.org/t/stm32cube-stm32xxx-hal-conf-h-include-search-path/19630/4), and as confirmed by me, pio always attempts to compile and link all files even if they are not relevant. This results in unnecessarily large binaries (as a best case) and failed builds (as a worst case; see link).

#### Steps to Reproduce

(the following is not entirely necessary, any project with a single file that is not included anywhere but fails to compile should suffice).

1.Generate project from stmcubemx
2. convert using [stm32pio]()
3. Add `board_build.stm32cube.custom_config_header = yes`
4. Try to build w/ `pio`

### Actual Results

Build errors.

### Expected Results

It should build fine.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
platform = ststm32
board = nucleo_f767zi
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
```

**Comment by valeros** [comment]
Hi @fazerlicourice7 ! I'm not completely sure this issue has something to do with the PlatformIO build system. Even though the `stm32pio` project uses PlatformIO under the good, it's still a completely separate project. TBH, I haven't used it yet, so I'm not really aware of their workflow. But the fact that PlatformIO compiles all files is not an issue actually, this is expected behavior. There is no way PlatformIO can guess what files are relevant to a specific project, that's why each framework source is compiled with the `-ffunction-sections`, `-fdata-sections` flags so the linker can later throw away unused symbols.

**Comment by fazerlicourice7** [comment]
I see.. Can't pio trace dependencies and includes recursively to select which sources to include?

**Comment by valeros** [comment]
> I see.. Can't pio trace dependencies and includes recursively to select which sources to include?

[Library Dependency Finder (LDF)](https://docs.platformio.org/en/latest/librarymanager/ldf.html) was developed exactly for this purpose. It works on the level of libraries/modules, but not in case with the frameworks which have their own build scripts.
