### ISSUE TITLE
Variety of boards, different results

### ISSUE THREAD

**Issue by jcw** [platformio/platform-ststm32#96]
There are a _lot_ of STM32 chip variants and boards. I've been trying to understand the different variations and how they are handled in PIO. Here's a surprising result:

```
$ arm-none-eabi-size .pioenvs/*/*.elf
   text	   data	    bss	    dec	    hex	filename
   6744	     28	    312	   7084	   1bac	.pioenvs/f103c8/firmware.elf
  11104	   2144	    940	  14188	   376c	.pioenvs/f103rb/firmware.elf
  11104	   2144	    940	  14188	   376c	.pioenvs/f103rb_nucleo/firmware.elf
```

The difference is due to an extra serial port driver. Which is good for a console on Nucleo boards (the on-board ST-Link acts as USB-serial interface), but the other two boards don't really differ: they both have an unknown board setup, so either a default serial driver on PA9/PA10 would make sense, or no serial driver at all (linked-in by default, that is).

This is the `platformio.ini` file for the above:

```
[env:f103c8]
platform = ststm32
board = genericSTM32F103C8
framework = mbed

[env:f103rb]
platform = ststm32
board = genericSTM32F103RB
framework = mbed

[env:f103rb_nucleo]
platform = ststm32
board = nucleo_f103rb
framework = mbed
```

And this is the `main.cpp` code:

```
#include <mbed.h>

DigitalOut led (PB_10);

int main () {
    while (1) {
        led = 0;
        wait_ms(100);
        led = 1;
        wait_ms(400); 
    }
}
```

Somewhat related: the generic STM32F103VE board does not support `mbed`, and there's no board definition for the STM32F103ZE (more pins, and more embedded peripherals).

I'm not suggesting every variation be included as individual boards (combinatorial explosion awaits...), but shouldn't there be some commonality in those generic boards which _are_ listed?

(perhaps this is more of a topic for the discussion forum...)

**Comment by ubis** [comment]
While generic boards doesn't really differ, `mbed` doesn't support them. 
It supports `Nucleo F103RB` and `BluePill` so, in order to bring support for generic one, we had to use: `generic f103rb == nucleo f103rb`, because both of them are using the same MCU.
And `generic f103c8/cb` is so popular, that it has it's own name - `BluePill`.

Technically speaking, you should be able to run the same firmware on `F103RB` which was compiled for `F103C8` and vice versa. Of course, additional stuff from `F103RB` won't work on `F103C8`, simply because that MCU doesn't have it.

As for other boards, yeah, there are many `F103` versions. Some of them are more popular, some aren't. We tend to add support for more popular boards. Sooner or later almost every board will be added.

**Comment by ivankravets** [comment]
Please reopen if you still need help
